services:
  postgres:
    image: postgres:17.4
    container_name: postgres_db_andamio
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_andamio:/var/lib/postgresql/data

  selenium:
    image: selenium/standalone-firefox:96.0.3-20220208
    ports:
      - "4444:4444"

  test:
    depends_on:
      - selenium
    command: mix test


volumes:
  postgres_data_andamio:
